### ISSUE TITLE
Unable to compile on Ubuntu LTS 14.04

### ISSUE THREAD

**Issue by avagin** [xemul/libct#1]
src/ct.c: In function ‘spawn_wait’:
src/ct.c:80:6: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
  read(pipe[0], &ret, sizeof(ret));
      ^
src/ct.c: In function ‘spawn_wake’:
src/ct.c:87:7: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
  write(pipe[1], &ret, sizeof(ret));
       ^
cc1: all warnings being treated as errors
make[1]: **\* [src/ct.o] Error 1
make: **\* [src/libct.so] Error 2
